import { NestFactory } from '@nestjs/core';
import { ecommerceModule } from './ecommerce.module';
import { Product } from './Products/Products.model'; 
import { Sequelize } from 'sequelize-typescript';
import { ProductType } from './Products/Products.model';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(ecommerceModule);
  const sequelize = app.get(Sequelize);

  await sequelize.sync({ alter: true });
const products = [
  {
    name: 'Reflex Plus Adult Cat Food Salmon',
    gender: '',
    color: 'Salmon',
    price: 140000,
    breed: 'Dog Food',
    age: '385gm',
    imageUrl: '/images/reflexplusadult.png',
    sku: 'P0009',
    vaccinated: false,
    dewormed: false,
    cert: false,
    microchip: false,
    location: false,
    additionalInformation: '',
    category: ProductType.PRODUCT,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Cute Pet Cat Warm Nest',
    gender: '',
    color: '',
    price: 410000,
    breed: 'Toy',
    age: '',
    imageUrl: '/images/scratchingtoy.png',
    sku: 'P0010',
    vaccinated: false,
    dewormed: false,
    cert: false,
    microchip: false,
    location: false,
    additionalInformation: '',
    category: ProductType.PRODUCT,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
    {
    name: 'Cat scratching ball toy kitten sisal rope ball',
    gender: '',
    color: '',
    price: 1100000,
    breed: 'Toy',
    age: '',
    imageUrl: '/images/cutepet.png',
    sku: 'P0030',
    vaccinated: false,
    dewormed: false,
    cert: false,
    microchip: false,
    location: false,
    additionalInformation: '',
    category: ProductType.PRODUCT,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
    {
    name: 'NaturVet Dogs - Omega-Gold Plus Salmon Oil',
    gender: '',
    color: '',
    price: 350000,
    breed: 'Dog Food',
    age: '385gm',
    imageUrl: '/images/naturvet.png',
    sku: 'P0030',
    vaccinated: false,
    dewormed: false,
    cert: false,
    microchip: false,
    location: false,
    additionalInformation: '',
    category: ProductType.PRODUCT,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },

      {
    name: 'Costumes Fashion Pet Clother Cowboy Rider',
    gender: '',
    color: '',
    price: 500000,
    breed: 'Costume',
    age: '1,5kg',
    imageUrl: '/images/costumesfashion.png',
    sku: 'P0050',
    vaccinated: false,
    dewormed: false,
    cert: false,
    microchip: false,
    location: false,
    additionalInformation: '',
    category: ProductType.PRODUCT,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },

      {
    name: 'Costumes Chicken Drumsti ck Headband',
    gender: '',
    color: '',
    price: 400000,
    breed: 'Costume',
    age: '',
    imageUrl: '/images/costumeschicken.png',
    sku: 'P0040',
    vaccinated: false,
    dewormed: false,
    cert: false,
    microchip: false,
    location: false,
    additionalInformation: '',
    category: ProductType.PRODUCT,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },

  {
    name: 'Pomeranian White',
    gender: 'Male',
    color: 'white',
    price: 690000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO231.png',
    sku: 'MO231',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Healthy and playful',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Poodle Tiny Yellow',
    gender: 'Female',
    color: 'Yellow',
    price: 390000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO502.png',
    sku: 'MO502',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Friendly temperament',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Poodle Tiny Sepia',
    gender: 'Male',
    color: 'Sepia',
    price: 400000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO102.png',
    sku: 'MO102',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Rare color variant',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Alaskan Malamute Grey',
    gender: 'Male',
    color: 'Grey',
    price: 890000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO512_alaskan.png',
    sku: 'MO512A',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Large breed, active',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Pembroke Corgi Cream',
    gender: 'Male',
    color: 'Cream',
    price: 790000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO231_pembroke.png',
    sku: 'MO231C',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Corgi with cream coat',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Pembroke Corgi Tricolor',
    gender: 'Male',
    color: 'Tricolor',
    price: 900000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO502tricolor.png',
    sku: 'MO502T',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Energetic and loyal',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Pomerian White',
    gender: 'Female',
    color: 'White',
    price: 650000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO231_pomerian.png',
    sku: 'MO231F',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Compact and calm',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
  {
    name: 'Poodle Tiny Dairy Cow',
    gender: 'Male',
    color: 'Cow',
    price: 500000000,
    breed: 'Tiny',
    age: '02 months',
    imageUrl: '/images/MO512_poodle.png',
    sku: 'MO512',
    vaccinated: true,
    dewormed: true,
    cert: true,
    microchip: true,
    location: true,
    additionalInformation: 'Unique pattern',
    category: ProductType.PET,
    publishedAt: new Date('2025-05-09T00:00:00-03:00'),
  },
];


  await Product.bulkCreate(products);
  console.log('✅ Produtos inseridos com sucesso!');

  await app.close();
}

bootstrap();